on:
    workflow_call:
        secrets:
            DEPLOY_HOOK_URL:
                required: true

jobs:
    deploy:
        runs-on: ${{ vars.runner || 'ubuntu-24.04' }}
        steps:
            - name: deploy
              env:
                  deploy_url: ${{ secrets.DEPLOY_HOOK_URL }}
              run: curl "$deploy_url"
